[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
  "cd backend",
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements_simple.txt"
]

[phases.build]
cmds = [
  "cd backend",
  "pip install -r requirements_simple.txt"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 